# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 0
fib_1 = 1
fib_2 = 1
while fib_2 <= 4000000:
    fib_temp = fib_1 + fib_2
    if fib_temp % 2 == 0:
        sum += fib_temp
    fib_1 = fib_2
    fib_2 = fib_temp
print(sum)
